### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by grahamc** [packethost/vault-plugin-secrets-packet#3]
Currently, there is no (obvious) license.

**Comment by t0mk** [comment]
@vielmetti It's up to Packet, pick one. MPL 2.0 seems to be the choice of other Secrets Engine pluings for Vault 
https://github.com/hashicorp/vault-plugin-secrets-azure/blob/master/LICENSE

**Comment by vielmetti** [comment]
Agreed on a need for a license. I don't have any strong preferences, so long as the license is compatible with actual use and redistribution expectations. That said I imagine that MPL 2.0 is probably best simply for harmony with the other Secrets Engine plugins. @jacobsmith928 probably can say something with more authority.

**Comment by jacobsmith928** [comment]
MPL 2.0 is a good idea.  +1

**Comment by grahamc** [comment]
btw I think I'm the only third party contributor, and I pre-emptively license my changes in https://github.com/t0mk/vault-plugin-secrets-packet/pull/1 as whatever license you pick as long as it is on this list: https://opensource.org/licenses and if y'all want to pick a different license I'm open to it, but don't preemptively agree :P.

**Comment by vielmetti** [comment]
Closed by #7
